### ISSUE TITLE
LUA issue

### ISSUE THREAD

**Issue by piddi19900** [denishamann/ArenaStats#19] opened 2023-01-05 19:54 UTC
Hi,

I receive the following error when the arena game is finish:

Message: Interface\AddOns\ArenaStats\ArenaStats.lua:131: attempt to index a nil value
Time: Thu Jan  5 20:52:45 2023
Count: 1
Stack: Interface\AddOns\ArenaStats\ArenaStats.lua:131: attempt to index a nil value
[string "@Interface\AddOns\ArenaStats\ArenaStats.lua"]:131: in function `SetLastArenaRankingData'
[string "@Interface\AddOns\ArenaStats\ArenaStats.lua"]:177: in function `?'
[string "@Interface\AddOns\ArenaStats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArenaStats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ArenaStats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ArenaStats\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\ArenaStats\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetBattlefieldScoreFaction'
[string "@Interface_Wrath\FrameXML\WorldStateFrame.lua"]:559: in function `WorldStateScoreFrameTab_OnClick'
[string "@Interface_Wrath\FrameXML\WorldStateFrame.lua"]:61: in function <Interface_Wrath\FrameXML\WorldStateFrame.lua:58>
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2214: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2020: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1927: in function <Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\WorldStateFrame.lua"]:130: in function `WorldStateScoreFrame_Update'
[string "@Interface_Wrath\FrameXML\WorldStateFrame.lua"]:48: in function <Interface_Wrath\FrameXML\WorldStateFrame.lua:44>

**Comment by denishamann** [comment] 2023-01-06 10:16
Hi piddi19900,

Thank you for your bug report, we are investigating the issue and will try to fix it as soon as possible.

In the meantime, could you tell us the language of your wow client?

**Comment by piddi19900** [comment] 2023-01-06 10:24
Hi,

Thats great, thanks.

I play the German client on the server Venoxis.

Denis Hamann ***@***.***> schrieb am Fr., 6. Jan. 2023, 11:16:

**Comment by denishamann** [comment] 2023-01-06 15:57
Thanks! For now, all people that report this issue are using a german client. I'll need to switch my language in order to debug. I'll keep you posted.

**Comment by denishamann** [comment] 2023-01-06 15:58
Certainly a duplicate of https://github.com/denishamann/ArenaStats/issues/18

**Comment by denishamann** [comment] 2023-01-10 19:29
Fixed in version 0.2.2, you can download it or it will be available on curse very soon.

**Closed by denishamann** 2023-01-10 19:29 UTC

**Comment by piddi19900** [comment] 2023-01-10 21:50
Great thx

Denis Hamann ***@***.***> schrieb am Di., 10. Jan. 2023,
20:29:

**Comment by piddi19900** [comment] 2023-01-12 22:18
Hi, got another one, when I finish a bg:

Message: ...AddOns\ArenaStats\Libs\LibRaces-1.0\LibRaces-1.0.lua:77:
assertion failed!
Time: Thu Jan 12 23:17:21 2023
Count: 1
Stack: ...AddOns\ArenaStats\Libs\LibRaces-1.0\LibRaces-1.0.lua:77:
assertion failed!
[string "=[C]"]: in function `assert'
[string
***@***.***\AddOns\ArenaStats\Libs\LibRaces-1.0\LibRaces-1.0.lua"]:77: in
function <...AddOns\ArenaStats\Libs\LibRaces-1.0\LibRaces-1.0.lua:76>
[string
***@***.***\AddOns\ArenaStats\Libs\LibRaces-1.0\LibRaces-1.0.lua"]:156: in
function `GetRaceToken'
[string ***@***.***\AddOns\ArenaStats\ArenaStats.lua"]:131: in function
`SetLastArenaRankingData'
[string ***@***.***\AddOns\ArenaStats\ArenaStats.lua"]:190: in function `?'
[string
***@***.***\AddOns\ArenaStats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
in function <...ats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string
***@***.***\AddOns\ArenaStats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
in function <...ats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string
***@***.***\AddOns\ArenaStats\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64:
in function `Fire'
[string
***@***.***\AddOns\ArenaStats\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in
function <...AddOns\ArenaStats\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetBattlefieldScoreFaction'
[string ***@***.***_Wrath\FrameXML\WorldStateFrame.lua"]:559: in function
`WorldStateScoreFrameTab_OnClick'
[string ***@***.***_Wrath\FrameXML\WorldStateFrame.lua"]:61: in function
<Interface_Wrath\FrameXML\WorldStateFrame.lua:58>
[string "=[C]"]: in function `Show'
[string ***@***.***_Wrath\FrameXML\UIParent.lua"]:2214: in function
`SetUIPanel'
[string ***@***.***_Wrath\FrameXML\UIParent.lua"]:2020: in function
`ShowUIPanel'
[string ***@***.***_Wrath\FrameXML\UIParent.lua"]:1927: in function
<Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string ***@***.***_Wrath\FrameXML\UIParent.lua"]:2733: in function
`ShowUIPanel'
[string ***@***.***_Wrath\FrameXML\WorldStateFrame.lua"]:130: in function
`WorldStateScoreFrame_Update'
[string ***@***.***_Wrath\FrameXML\WorldStateFrame.lua"]:48: in function
<Interface_Wrath\FrameXML\WorldStateFrame.lua:44>

Locals: <none>

Am Di., 10. Jan. 2023 um 22:50 Uhr schrieb Pkry ***@***.***>:
